"""create agents and agent_tools

Revision ID: af8b15d310a2
Revises: aa0735f82794
Create Date: 2025-12-30 14:29:44.172610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8b15d310a2'
down_revision: Union[str, Sequence[str], None] = 'aa0735f82794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_agents_tenant_name')
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('agent_tools',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'tool_id', name='uq_agent_tools_tenant_agent_tool')
    )
    op.create_index(op.f('ix_agent_tools_tenant_id'), 'agent_tools', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tools_tenant_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
